[package]
name = "binboh"
version = "0.1.0"
authors = ["Tillerino <tillmann.gaida@gmail.com>"]
edition = '2021'

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "5"
indexmap = "2"
blake3 = "1"
